### ISSUE TITLE
Ship the icons with Firefox

### ISSUE THREAD

**Issue by vanillajonathan** [FirefoxUX/icons#50]
Ship the icons with Firefox, reachable through the `chrome://` URI.

This allows Firefox to internally make use of the icons.
It also allows third-party WebExtension developers to reference the icons directly without redundantly bundling the icons with every WebExtension.

**Comment by nt1m** [comment]
> Ship the icons with Firefox, reachable through the chrome:// URI.

I don't think this is the right approach. If we start doing that, we won't be able to remove or rename icons because an add-on was relying on a specific url.

A better approach would be for the add-on to pull the icons from a repo/package, then update it regularly. We started providing an npm package that you might want to look at: https://www.npmjs.com/package/photon-icons

**Comment by nt1m** [comment]
Maybe @bwinton has thoughts on this, as he worked on the browser_style stuff.

**Comment by vanillajonathan** [comment]
Note that the `chrome://` URI already exposes resources such as style sheets, icons and images today that may already be used by third-party WebExtensions (or less likely websites) which may break if these were to change.

I wasn't aware of that package, thanks for pointing out, I'll look into it. :)
