### ISSUE TITLE
The Dictionaries icon used for the Add-ons Manager is unclear (or has some sort of artefact)

### ISSUE THREAD

**Issue by jorgk3** [FirefoxUX/icons#56]
The Dictionaries icon used for the Add-ons Manager looks weird. What is that little thing on the bottom right? A check mark in a circle? Or a download arrow in a circle?

On the screen it looks like this:
![1433654](https://user-images.githubusercontent.com/8466558/35505664-19093262-04e7-11e8-88af-aae5586e30f1.png)

If it's meant to be an arrow, perhaps the arrow "body" should be white.

**Comment by nt1m** [comment]
The arrow should probably be pixel-snapped.

/cc @brassy- @aminalhazwani

**Comment by brassy-** [comment]
Thanks for the mention, @nt1m!


@jorgk3 the icon currently in use in the add-ons manager has been scaled, that's why it looks a bit off :-/
However, since we're planning to relocate some content related to dictionaries and languages in the next future (where  no icon is going to be needed) I don't see the need to redraw it.
